version: '3.4'
services:
  mysql:
    container_name: "mysql"
    image: "mysql:latest"
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
      - ./data/run/mysqld:/var/run/mysqld:rw
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: swoole
      MYSQL_PASSWORD: swoole
  pgsql:
    image: postgres:14
    container_name: "pgsql"
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: test
      POSTGRES_PASSWORD: root
  oracle:
    image: gvenzl/oracle-free:slim
    container_name: "oracle"
    environment:
      ORACLE_PASSWORD: oracle
    ports:
      - "1521:1521"
  redis:
    container_name: "redis"
    image: "redis:latest"
    volumes:
      - ./data/redis:/var/lib/redis:rw
      - ./data/run/redis:/var/run/redis:rw
    sysctls:
        net.core.somaxconn: 65535
  httpbin:
    container_name: "httpbin"
    image: "arnaudlacour/httpbin"
  tinyproxy:
    container_name: "tinyproxy"
    image: "kalaksi/tinyproxy"
  golang-h2demo:
    container_name: "golang-h2demo"
    image: "phpswoole/golang-h2demo"
  socks5:
    container_name: "socks5"
    image: "serjs/go-socks5-proxy"
    ports:
      - "1080:1080"
  ftp:
    container_name: "ftp"
    image: "crazymax/pure-ftpd"
    environment:
      FTP_USER_NAME: admin
      FTP_USER_PASS: admin
      FTP_USER_HOME: /home/swoole

